[package]
name = "image-sender"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
env_logger = "0.8"
image = "0.23"
log = "0.4"
nb = "1.0"
structopt = "0.3"

cyberpixie-proto = { path = "../../crates/proto" }
cyberpixie-std-transport = { path = "../../crates/std-transport" }
