[package]
name = "cyberpixie-esp32c3"
version = "0.2.0"
authors = ["Aleksey Sidorov <sauron1987@gmail.com>"]
edition = "2021"
resolver = "2"

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
nb = "1.0"
anyhow = "1"
cyberpixie-proto = { workspace = true }
cyberpixie-std-transport = { workspace = true }
embedded-hal = { workspace = true }
embedded-svc = { workspace = true }
esp-idf-hal = { workspace = true }
esp-idf-svc = { workspace = true }
esp-idf-sys = { workspace = true }
log = "0.4"
postcard = { version = "1", default-features = false, features = ["use-std"] }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
anyhow = "1"
embuild = { workspace = true }
