[package]
name = "cyberpixie-esp32c3"
version = "0.2.0"
authors = ["Aleksey Sidorov <sauron1987@gmail.com>"]
edition = "2021"
resolver = "2"

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
cyberpixie-wifi = { workspace = true }
embedded-hal = { workspace = true }
esp-idf-sys =  { workspace = true }

[build-dependencies]
anyhow = "1"
embuild = { workspace = true }
