[package]
name = "cyberpixie-esp32c3"
version = "0.2.0"
authors = ["Aleksey Sidorov <sauron1987@gmail.com>"]
edition = "2021"
resolver = "2"

[features]
pio = ["esp-idf-sys/pio"]

[dependencies]
anyhow = "1"
cyberpixie-core = { workspace = true }
cyberpixie-std-network = { workspace = true }
embedded-hal = { workspace = true }
embedded-io = "0.4"
embedded-svc = { workspace = true }
esp-idf-hal = { workspace = true }
esp-idf-svc = { workspace = true }
esp-idf-sys = { workspace = true }
heapless = "0.7"
log = "0.4"
nb = "1.0"
once_cell = "1.16"
postcard = { version = "1", default-features = false, features = ["use-std"] }
serde = { version = "1.0", features = ["derive"] }
smart-leds = "0.3"
ws2812-esp32-rmt-driver = { workspace = true }

[build-dependencies]
anyhow = "1"
embuild = { workspace = true }
