[package]
name = "cyberpixie_esp32c3"
version = "0.1.0"
authors = ["Aleksey Sidorov <sauron1987@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# Hardware support
esp-backtrace = { version = "0.7.0", features = ["esp32c3", "panic-handler", "exception-handler", "print-uart"] }
esp-hal-smartled = { version = "0.2.0", features = ["esp32c3"] }
esp-println = { version = "0.5.0", features = ["esp32c3"] }
hal = { package = "esp32c3-hal", version = "0.9.0" }

# Common
heapless = { workspace = true }
smart-leds = "0.3"

# Cyberpixie
# cyberpixie-app = { workspace = true }
