[workspace]
resolver = "2"

members = [
  "crates/core",
  "crates/network",
  "firmware/esp32-idf",
  "utils/cli",
  "application/rust",
]

default-members = ["crates/core", "crates/network"]

exclude = ["firmware/esp32-idf", "utils/image_sender", "application/rust"]

[workspace.dependencies]
# Workspace crates
cyberpixie-core = { path = "crates/core", features = ["std"] }
cyberpixie-std-network = { path = "crates/network" }

# Common dependencies
heapless = { version = "0.7" }
nb-utils = { git = "https://github.com/alekseysidorov/nb-utils.git", branch = "main" }
postcard = { version = "1.0", features = ["experimental-derive"] }
postcard-derive = "0.1.0"
