[workspace]
resolver = "2"

members = [
  # "application/rust",
  "boards/esp32/common",
  "boards/esp32/esp32c3",
  "boards/esp32/esp32s3",
  "crates/app",
  "crates/core",
  "crates/network",
  "crates/storage",
  "utils/cli",
  "utils/board",
]

default-members = [
  "crates/app",
  "crates/core",
  "crates/network",
  "crates/storage",
  "utils/cli",
  "utils/board",
]

exclude = [
  "application/rust",
]

[workspace.dependencies]
# Workspace crates
cyberpixie-app = { path = "crates/app" }
cyberpixie-core = { path = "crates/core" }
cyberpixie-embedded-storage = { path = "crates/storage" }
cyberpixie-esp-common = { path = "boards/esp32/common" }
cyberpixie-network = { path = "crates/network" }

# ESP dependencies
embassy-executor = { version = "0.3.0", features = ["nightly", "integrated-timers", "executor-thread"] }
embassy-net = { version = "0.1.0", features = ["nightly", "tcp", "udp", "dhcpv4", "medium-ethernet", "unstable-traits", "proto-ipv6"] }
embassy-sync = { version = "0.3.0", features = ["nightly"] }
embassy-time = { version = "0.1.1", features = ["nightly"] }
embedded-hal-async = { version = "=1.0.0-rc.1" }
embedded-io = { version = "0.5" }
embedded-io-adapters = "0.5.0"
embedded-io-async = "0.5.0"
embedded-svc = { version = "0.25", default-features = false }
esp-wifi = { git = "https://github.com/esp-rs/esp-wifi.git", rev = "b54310e", features = ["embedded-svc", "wifi", "embassy-net", "ipv6", "ble"] }
esp32c3-hal = { version = "0.12", features = ["async", "embassy"] }
esp32s3-hal = { version = "0.12", features = ["async", "embassy"] }
smoltcp = { version = "0.10.0", default-features = false, features = ["proto-ipv4", "proto-ipv6"] }
ws2812-async = { version = "0.1.0", git = "https://github.com/kalkyl/ws2812-async.git", rev = "200a752" }
