[workspace]
resolver = "2"
members = [
    "firmware", 
    "proto", 
    "esp8266-softap", 
]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
