[package]
name = "pixel-poi-firmware"
version = "0.1.0"
authors = ["Aleksei Sidorov <gorthauer87@yandex.ru>"]
edition = "2018"
resolver = "2"

[dependencies]
embedded-hal = "0.2"
gd32vf103xx-hal = "0.4.0"
nb = "1.0"
panic-halt = "0.2"
riscv = "0.6"
riscv-rt = "0.8"
smart-leds = "0.3"
ws2812-spi = { version = "0.4" }

[dependencies.prost]
version = "0.7"
default-features = false
features = ["prost-derive"]

[dependencies.linked_list_allocator]
default-features = false
version = "0.8.11"
features = ["const_mut_refs"]

[build-dependencies]
image = "0.23"
quote = "1.0"
syn = "1.0"
