[workspace]
resolver = "2"
members = [
    "firmware", 
    "proto", 
    "esp8266/device", 
    "esp8266/serial"
]

# exclude = ["esp8266/serial"]
# default-members = ["firmware", "esp8266/device"]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
