[workspace]
resolver = "2"

members = [
  "application/rust",
  "crates/app",
  "crates/core",
  "crates/network",
  "crates/storage",
  "firmware/esp32-idf",
  "firmware/esp32c3",
  "utils/cli",
]

default-members = ["crates/core", "crates/network"]

exclude = [
  "application/rust",
  "firmware/esp32-idf",
  "firmware/esp32c3",
  "utils/image_sender",
]

[workspace.dependencies]
# Workspace crates
cyberpixie-app = { path = "crates/app" }
cyberpixie-embedded-storage = { path = "crates/storage" }
cyberpixie-core = { path = "crates/core" }
cyberpixie-network = { path = "crates/network" }

# Common dependencies
heapless = { version = "0.7" }
nb-utils = { git = "https://github.com/alekseysidorov/nb-utils.git", branch = "main" }
postcard = { version = "1.0", features = ["experimental-derive"] }
postcard-derive = "0.1.0"
