[package]
name = "cyberpixie"
version = "0.4.0"
edition = "2021"

[dependencies]
esp-alloc = { version = "0.5.0" }
esp-backtrace = { version = "0.14.2", features = [
  "esp32c3",
  "exception-handler",
  "panic-handler",
  "println",
] }
esp-hal = { version = "0.22.0", features = ["esp32c3"] }
esp-hal-embassy = { version = "0.5.0", features = ["esp32c3"] }
esp-println = { version = "0.12.0", features = ["esp32c3", "log"] }
esp-wifi = { version = "0.11.0", default-features = false, features = [
  "esp32c3",
  "utils",
  "wifi",
  "esp-alloc",
  "log",
] }

embassy-executor = { version = "0.6.0", features = ["task-arena-size-12288"] }
embassy-net = { version = "0.4.0", features = ["tcp", "udp", "dhcpv4", "medium-ethernet"] }
embassy-time = { version = "0.3.1", features = ["generic-queue-8"] }
embedded-hal-async = "1.0.0"
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
smoltcp = { version = "0.11.0", default-features = false, features = [
  "medium-ethernet",
  "proto-dhcpv4",
  "proto-igmp",
  "proto-ipv4",
  "socket-dhcpv4",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }

critical-section = "1.2.0"
heapless = { version = "0.8.0", default-features = false }
log = { version = "0.4" }
smart-leds = "0.4"
static_cell = { version = "2.1", features = ["nightly"] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
