[workspace]
resolver = "2"

members = [
    "crates/core",
    "crates/esp8266-softap", 
    "crates/nb_utils",
    "crates/proto", 
    "crates/simple-clock",
    "crates/stdio-serial",
    "utils/image_sender",
]
exclude = ["firmware"]
