[workspace]
resolver = "2"

members = [
  "application/rust",
  "crates/app",
  "crates/core",
  "crates/network",
  "crates/storage",
  "utils/cli",
]

default-members = [
  "crates/app",
  "crates/core",
  "crates/network",
  "crates/storage",
  "utils/cli",
]

[workspace.dependencies]
# Workspace crates
cyberpixie-app = { path = "crates/app" }
cyberpixie-embedded-storage = { path = "crates/storage" }
cyberpixie-core = { path = "crates/core" }
cyberpixie-network = { path = "crates/network" }
cyberpixie-esp-common = { path = "boards/esp32/common" }

# ESP dependencies
smoltcp = { version = "0.9.0", default-features = false, features = ["proto-ipv4", "proto-ipv6"] }
