[package]
name = "esp8266-device"
version = "0.1.0"
authors = ["Aleksei Sidorov <gorthauer87@yandex.ru>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2"
gd32vf103xx-hal = "0.4"
nb = "1.0"
riscv-rt = "0.8"

# For main util
[dependencies.aurora-led-firmware]
path = "../../firmware"
