name: "Install dependencies"

runs:
  using: "composite"
  steps: 
    - name: Installing packages
      shell: bash
      run: |
        sudo apt update
        sudo apt install libudev-dev zlib1g-dev
    - name: Setup environment
      shell: bash
      run: export CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu
