[package]
name = "image-sender"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
cyberpixie-proto = { path = "../../crates/proto" }
env_logger = "0.8"
image = "0.23"
log = "0.4"
structopt = "0.3"
