[package]
name = "image-sender"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1"
cyberpixie-proto = { workspace = true }
cyberpixie-std-transport = { workspace = true }
env_logger = "0.10"
image = "0.24"
log = "0.4"
nb = "1.0"
structopt = "0.3"
