[package]
name = "cyberpixie-qml"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
anyhow = "1.0"
cstr = "0.2"
env_logger = "0.8"
log = "0.4"
qmetaobject = "0.2.2"

cyberpixie-std-transport = { path = "../../crates/std-transport" }
cyberpixie-proto = { path = "../../crates/proto" }
