[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --partition-table assets/partitions.csv"

# The best discovered optimization flags without stability issues.
[profile.release]
opt-level = "s"
lto = "thin"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "s"
lto = "thin"

[unstable]
build-std = ["core"]
