[package]
name = "cyberpixie-embedded-storage"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyberpixie-app = { workspace = true }
embedded-io = { workspace = true }
embedded-storage = { workspace = true }
endian_codec = { workspace = true }
heapless = { workspace = true }
log = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
image = { workpace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[features]
std = ["embedded-io/std"]

[[test]]
name = "main"
path = "tests/main.rs"
required-features = ["std"]
