[build]
target = "xtensa-esp32s3-none-elf"

# The best discovered optimization flags without stability issues.
[profile.release]
opt-level = 3
lto = "thin"

[profile.dev]
debug = true  # Symbols are nice and they don't increase the size on Flash
opt-level = 3
lto = "thin"
