[package]
name = "cyberpixie-proto"
version = "0.1.0"
edition = "2018"

[dependencies]
nb = "1.0"
postcard = { version = "0.6.1", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }

[dev-dependencies]
embedded-hal = "0.2"
serialport = "4"
esp8266-softap = { path = "../esp8266-softap" }
stdio-serial = { path = "../stdio-serial", features = ["std", "dprint"] }
