[package]
name = "cyberpixie"
version = "0.1.0"
edition = "2018"

[dependencies]
embedded-hal = "0.2"
heapless = "0.7"
nb = "1.0"
serde = { version = "1", default-features = false, features = ["derive"] }
smart-leds = "0.3"

stdio-serial = { path = "../stdio-serial" }
cyberpixie-proto = { path = "../proto" }


[dev-dependencies]
