[package]
name = "cyberpixie-firmware"
version = "0.1.0"
authors = ["Aleksei Sidorov <gorthauer87@yandex.ru>"]
edition = "2018"
resolver = "2"

[dependencies]
embedded-hal = "0.2"
embedded-sdmmc = "0.3"
endian_codec = "0.1"
gd32vf103xx-hal = "0.4"
nb = "1.0"
riscv = "0.6"
riscv-rt = "0.8"
smart-leds = "0.3"
ws2812-spi = { version = "0.4" }

stdio-serial = { path = "../crates/stdio-serial" }
esp8266-softap = { path = "../crates/esp8266-softap" }
cyberpixie-proto = { path = "../crates/proto" }

[dependencies.linked_list_allocator]
version = "0.9"
default-features = false
features = ["const_mut_refs"]

[build-dependencies]
image = { version = "0.23", optional = true }
quote = { version = "1.0", optional = true }
syn = { version = "1.0", optional = true }

[features]
generate_img = ["image", "quote", "syn"]
